before_script:
  - go env -w GO111MODULE=on
  - go env -w GOPROXY="https://goproxy.cn,direct"

stages:
  - format
  - ut
  - dockerbuild

format:
  stage: format
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

unittest:
  stage: ut
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

docker-build:
  stage: dockerbuild
  image: docker:20.10.12
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker login -u $CI_REGISTRY_USERNAME -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" .
    - docker push "$CI_REGISTRY_IMAGE${tag}"




