variables:
  REPO_NAME: mini_cmux

before_script:
  - go env -w GO111MODULE=on
  - go env -w GOPROXY="https://goproxy.cn,direct"
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
#  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME
stages:
  - format
  - ut
  - dockerbuild

format:
  stage: format
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)

unittest:
  stage: ut
  script:
    - go test -race $(go list ./... | grep -v /vendor/)

docker-build:
  stage: dockerbuild
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE${tag}" -f resource/Dockerfile .
    - docker push "$CI_REGISTRY_IMAGE${tag}"
  rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - resource/Dockerfile




