apiVersion: apps/v1
kind: Deployment
metadata:
  name: minicmux
  namespace: default
  labels:
    app: minicmux
    version: 0.0.1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: minicmux
  template:
    metadata:
      labels:
        app: minicmux
    spec:
      containers:
        - name: minicmux
          image: registry.gitlab.com/ljhhhhhh1224/mini_cmux:latest
          ports:
            - containerPort: 23456


